from enum import nonmember
# -*- coding: utf-8 -*-
"""IMCipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PA-4w1RV_EMogSC1FVUrDARDNifA00FX
"""

import ipywidgets as widgets
from IPython.display import display, HTML

# Estilização CSS Dark
style = """
<style>

    .main-container {
        background-color: #2c3e50;
        color:#000080;
        background-image: url("https://lucianaspina.com.br/wp-content/uploads/2018/05/IMC.jpg");
        background-size: cover;
        background-position: center;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        font-family: Arial, sans-serif;
        font-size: 16px;
        font-weight: bold;
        padding: 300px;

    }
    /* Borda preta nos labels e nos números (readout) */
    .widget-label, .widget-readout {
        color: #ffffff !important;
        font-weight: bold !important;
        text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000, 1px 1px 1px #000 !important;
    }

    .custom-button {
        background-color: #007bff;
        color:#F5F5F5;
        font-weight: bold;
        border-radius: 8px;
        text-shadow: 1px 1px 2px #000;
    }

    .output-area {
        margin-top: 15px;
        padding: 10px;
        background-color: #ffffff;
        border: 1px solid #ffffff;
        border-left: 5px solid #007bff;
        border-radius: 4px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        color: black;
        font-weight: bold
    }
</style>
"""
display(HTML(style))

# Widgets de Entrada
nome_w = widgets.Text(description='Nome:', placeholder='Digite seu nome')
idade_w = widgets.IntSlider(description='Idade:', min=0, max=120, value=25)
peso_w = widgets.FloatText(description='Peso (kg):', value=0.0)
altura_w = widgets.FloatText(description='Altura (m):', value=0.0)

btn_calcular = widgets.Button(description='Calcular Resultados', button_style='primary')
btn_calcular.add_class("custom-button")

btn_limpar = widgets.Button(description='Limpar Campos', button_style='info')
btn_limpar.add_class("custom-button")

out = widgets.Output()

def processar_dados(b):
    with out:
        out.clear_output()
        nome = nome_w.value
        idade = idade_w.value
        peso = peso_w.value
        altura = altura_w.value

        print(f"Olá, {nome}!")
        print(f"Status: {'Maior de idade' if idade >= 18 else 'Menor de idade'}")

        # Classificação de Altura
        if altura <= 1.65: cat_altura = "Baixo(a)"
        elif altura <= 1.79: cat_altura = "Mediano(a)"
        else: cat_altura = "Alto(a)"

        # Cálculo IMC
        if altura > 0:
            imc = peso / (altura ** 2)
            if imc < 18.5: classe = "Abaixo do peso"
            elif imc < 24.9: classe = "Peso normal"
            elif imc < 29.9: classe = "Sobrepeso"
            else: classe = "Obesidade"

            display(HTML(f"""
                <div class='output-area'>
                    <b>Altura:</b> {cat_altura}<br>
                    <b>IMC:</b> {imc:.2f} ({classe})
                </div>
            """))
        else:
            print("Erro: Altura inválida.")

def limpar_campos(b):
    with out:
        out.clear_output()
        nome_w.value = ''
        idade_w.value = 25
        peso_w.value = 0.0
        altura_w.value = 0.0

btn_calcular.on_click(processar_dados)
btn_limpar.on_click(limpar_campos)

# Layout
form = widgets.VBox([nome_w, idade_w, peso_w, altura_w, widgets.HBox([btn_calcular, btn_limpar]), out])
form.add_class("main-container")
display(form)
