# -*- coding: utf-8 -*-
"""IMCipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PA-4w1RV_EMogSC1FVUrDARDNifA00FX
"""

import ipywidgets as widgets
from IPython.display import display, HTML

# Estilização CSS Dark
style = """
<style>
    .main-container {
        background-color: #1e1e1e;
        padding: 20px;
        border-radius: 15px;
        border: 1px solid #333;
        color: #ffffff;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .widget-label { color: #ffffff !important; font-weight: bold; }
    .custom-button {
        background-color: #007bff !important;
        color: white !important;
        font-weight: bold !important;
        border-radius: 8px !important;
    }
    .output-area {
        margin-top: 15px;
        padding: 10px;
        background-color: #2d2d2d;
        border-left: 5px solid #007bff;
        border-radius: 4px;
    }
</style>
"""
display(HTML(style))

# Widgets de Entrada
nome_w = widgets.Text(description='Nome:', placeholder='Digite seu nome')
idade_w = widgets.IntSlider(description='Idade:', min=0, max=120, value=25)
peso_w = widgets.FloatText(description='Peso (kg):', value=70.0)
altura_w = widgets.FloatText(description='Altura (m):', value=1.75)

btn_calcular = widgets.Button(description='Calcular Resultados', button_style='primary')
btn_calcular.add_class("custom-button")

out = widgets.Output()

def processar_dados(b):
    with out:
        out.clear_output()
        nome = nome_w.value
        idade = idade_w.value
        peso = peso_w.value
        altura = altura_w.value

        print(f"Olá, {nome}!")
        print(f"Status: {'Maior de idade' if idade >= 18 else 'Menor de idade'}")

        # Classificação de Altura
        if altura <= 1.65: cat_altura = "Baixo(a)"
        elif altura <= 1.79: cat_altura = "Mediano(a)"
        else: cat_altura = "Alto(a)"

        # Cálculo IMC
        if altura > 0:
            imc = peso / (altura ** 2)
            if imc < 18.5: classe = "Abaixo do peso"
            elif imc < 24.9: classe = "Peso normal"
            elif imc < 29.9: classe = "Sobrepeso"
            else: classe = "Obesidade"

            display(HTML(f"""
                <div class='output-area'>
                    <b>Altura:</b> {cat_altura}<br>
                    <b>IMC:</b> {imc:.2f} ({classe})
                </div>
            """))
        else:
            print("Erro: Altura inválida.")

btn_calcular.on_click(processar_dados)

# Layout
form = widgets.VBox([nome_w, idade_w, peso_w, altura_w, btn_calcular, out])
form.add_class("main-container")
display(form)